# Generated by Django 4.1.6 on 2023-02-11 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Client Company"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("self_s", "small_sales"),
                            ("dist", "distributor"),
                            ("brand", "brand_sales"),
                            ("cust", "end_user"),
                            ("fac", "factory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.CharField(max_length=200, verbose_name="Company Owner"),
                ),
                (
                    "owner_phone",
                    models.CharField(max_length=25, verbose_name="Owner Phone"),
                ),
                ("address", models.CharField(max_length=200)),
                ("zip_code", models.CharField(max_length=15, verbose_name="Zip Code")),
                ("web", models.URLField(blank=True, verbose_name="Website Address")),
                (
                    "manager_name",
                    models.CharField(max_length=25, verbose_name="Manager"),
                ),
                (
                    "manager_phone",
                    models.CharField(max_length=25, verbose_name="Manager Phone"),
                ),
                (
                    "manager_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Manager Email"
                    ),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Product")),
                ("code", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("moq", models.IntegerField()),
                ("lead_time", models.DurationField(max_length=200)),
                (
                    "quality_standard",
                    models.CharField(max_length=200, verbose_name="Standard"),
                ),
                (
                    "design_size",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="width x depth x height",
                    ),
                ),
                ("design_file", models.FileField(upload_to="")),
                ("material", models.TextField()),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Vendor")),
                (
                    "owner",
                    models.CharField(max_length=200, verbose_name="Company Owner"),
                ),
                (
                    "owner_phone",
                    models.CharField(max_length=25, verbose_name="Owner Phone"),
                ),
                ("address", models.CharField(max_length=200)),
                ("zip_code", models.CharField(max_length=15, verbose_name="Zip Code")),
                ("web", models.URLField(blank=True, verbose_name="Website Address")),
                (
                    "manager_name",
                    models.CharField(max_length=25, verbose_name="Manager"),
                ),
                (
                    "manager_phone",
                    models.CharField(max_length=25, verbose_name="Manager Phone"),
                ),
                (
                    "manager_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Manager Email"
                    ),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Order Number")),
                (
                    "code_order",
                    models.CharField(max_length=200, verbose_name="Order Code"),
                ),
                (
                    "code_shipping",
                    models.CharField(max_length=200, verbose_name="Shipping Code"),
                ),
                ("price", models.IntegerField()),
                ("lead_time", models.DurationField(max_length=200)),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.client"
                    ),
                ),
                (
                    "item_list",
                    models.ManyToManyField(related_name="ordered_item", to="base.item"),
                ),
                (
                    "item_price",
                    models.ManyToManyField(
                        related_name="ordered_price", to="base.item"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.vendor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.vendor"
            ),
        ),
    ]
