# Generated by Django 4.1.6 on 2023-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_client_assistant_item_assistant_order_assistant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="design_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="design_file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
